/* eslint-disable */
// tslint:disable
/**
 * nautible-app-examples API
 * nautible examples Service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface RestExamplesServiceApi {
	hello: () => Promise<HelloResponse>
}

export type HelloResponse = Hello200Response

export interface Hello200Response {
	status: 200
	body: string
	headers?: never
}

