/* eslint-disable */
// tslint:disable
/**
 * nautible-app-examples API
 * nautible examples Service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import * as healthCheckService from './api/healthCheckService/types'
import * as restExamplesService from './api/restExamplesService/types'

export interface ApiImplementation {
	healthCheckService: healthCheckService.HealthCheckServiceApi
	restExamplesService: restExamplesService.RestExamplesServiceApi
}
