# OpenAPI Generator Plus generator configuration
#
# The path (relative to this configuration file) or a URL for your API specification
inputPath: api/examples.yaml

# The path (relative to this configuration file) where the generated API should be output
outputPath: src/openapi_server

# The name of the generator template used
generator: "@openapi-generator-plus/typescript-express-passport-server-generator"
