# coding: utf-8

"""
    nautible-app-examples API

    nautible examples Service

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.health_check_service_api import router as HealthCheckServiceApiRouter
from openapi_server.apis.rest_examples_service_api import router as RestExamplesServiceApiRouter

app = FastAPI(
    title="nautible-app-examples API",
    description="nautible examples Service",
    version="1.0.0",
)

app.include_router(HealthCheckServiceApiRouter)
app.include_router(RestExamplesServiceApiRouter)
