/* eslint-disable */
// tslint:disable
/**
 * nautible-app-examples API
 * nautible examples Service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface HealthCheckServiceApi {
	healthz: () => Promise<HealthzResponse>
}

export type HealthzResponse = Healthz200Response | Healthz503Response

export interface Healthz200Response {
	status: 200
	body: string
	headers?: never
}

export interface Healthz503Response {
	status: 503
	body?: never
	headers?: never
}

